### ISSUE TITLE
[feature request] Sniffing Support for QUIC Connections

### ISSUE THREAD

**Issue by molink36** [v2fly/v2ray-core#1000]
V2Ray has already implemented extraction of server names from TLS and HTTP over TCP connections. However, a growing number of websites are moving from traditional TLS and HTTP to QUIC protocol over UDP.
It would be great if V2Ray was able to sniff domain names from protocol.

**Comment by xiaokangwang** [comment]
Sniffing is not possible since a single UDP connection is used to transfer data towards multiple destinations, and sniffing in V2Ray works in a connection by connection basis. The connection must be MITMed to be split it into distinct stream, otherwise it would be impossible to route QUIC connections based on its destination.
