### ISSUE TITLE
建议能否将fakeip的ttl值设置为1

### ISSUE THREAD

**Issue by kulongwangzhi85** [v2fly/v2ray-core#2139]
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
A unified platform for anti-censorship.

通过抓包查看到，使用里fakeip的ttl为600秒，是不是太大了？
标准fakeip的ttl=1  ？？

主要是因为在使用第三方dns服务器时，无法单独关闭对fakeip的缓存。
这样只能将v2ray 的dns方在第三方dns前

本想术业有专攻，将第三方dns服务器放前，v2ray只解析gfw的fakedns。

**Comment by mydogshitgold** [comment]
I suppose you want to use FakeDNS for a specific set of domains, and other **real** dedicated DNS resolver for the rest.

If that's the case, change TTL is probably not the right solution for your problem. Also, It is not ideal to make the dedicated DNS resolver to forward requests to the built-in DNS resolver because this may cause cache conflict and poisoning.

Instead, you should make the built-in DNS resolver response DNS requests of that set of domains with FakeIP and forwards the rest to dedicated DNS resolver.

```json
{
  "dns": {
    "servers": [
      "localhost",
      {
        "address": "fakedns",
        "domains": [
          "geosite:geolocation-!cn"
        ]
      }
    ]
  }
}
```
I suggest you to read the whole [configuration documentations](https://www.v2fly.org/config/overview.html) to help you better understand V2Ray.

---
p.s. Unfortunately, your question looks like an [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem).

**Comment by AkinoKaede** [comment]
V2Ray's DNS has been refactored a lot, I think it can meet your needs.
