### ISSUE TITLE
通过 V2Ray  DNS 服务查询 非（A  AAAA） DNS 记录时，V2Ray 发出非预期的地址访问。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [v2fly/v2ray-core#2342]
## 你正在使用哪个版本的 V2Ray？

v2ray 5.4   linux-arm32-v5 

## 你的使用场景是什么？
测试 DNS 查询 

## 你看到的异常现象是什么？
局域网 设备向通过 v2ray 提供的DNS 端口查询 DNS    非 （A  AAAA）  记录时，
v2ray 内部映射的虚拟地址，被 v2ray 意外发出该地址的访问。
测试了 5.4 版和5.3 版，Win x86_64 和 linux-arm32-v5 平台。
其中 linux-arm32-v5 都有这个问题，x86_64 没有

复现流程描述，已下面的配置为例。

1. 服务端启动 v2ray 
2. 局域网 用户  发出 DNS NS 记录 查询 `doggo.exe @udp://服务端IP:13253   wsdfdf.caac  -t NS`
3. 用户 DNS 查询 失败。
4. 在局域网 网关 截取到 服务端 访问 253.253.253.253:25353

## 你期待看到的正常表现是怎样的？
知道 v2ray  只能查询 A  AAAA，但也不能有非预期访问。

一些公司的软件也会查询其他类型的DNS记录，会给用户造成困扰。

这应该是个安全问题， 不同平台表现也不一致。

希望能解决。
## 请附上你的配置

**服务端配置：**
//有一些标签没有配置，是测试时精简的，这就是测试的配置。
```javascript
// 在这里附上服务器端配置文件

{
    "dns": {
        "servers": [
            "fakedns",
            "8.8.8.8",
            "1.1.1.1"
        ]
    },
    "fakedns": {
        "ipPool": "172.20.0.0/16",
        "poolSize": 65534
    },
    "inbounds": [
        {
            "port": 13253,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "253.253.253.253",
                "network": "udp",
                "port": 25353
            },
            "tag": "FakeDns-In"
        }
    ],
    "outbounds": [
        {
            "protocol": "dns",
            "tag": "Dns-Out"
        }
    ],
    "routing": {
        "balancers": [
            {
                "selector": [
                    "bwgkvm1"
                ],
                "tag": "Proxy"
            }
        ],
        "rules": [
            {
                "balancerTag": "Proxy",
                "inboundTag": [
                    "TransParent-In"
                ],
                "network": "tcp,udp",
                "type": "field"
            },
            {
                "address": "253.253.253.253",
                "inboundTag": [
                    "FakeDns-In"
                ],
                "network": "udp",
                "outboundTag": "Dns-Out",
                "port": 25353,
                "type": "field"
            },
            {
                "balancerTag": "Proxy",
                "ip": [
                    "1.1.1.1/32",
                    "1.0.0.1/32",
                    "8.8.8.8/32",
                    "8.8.4.4/32"
                ],
                "type": "field"
            },
            {
                "balancerTag": "Proxy",
                "network": "tcp,udp",
                "type": "field"
            },
            {
                "ip": [
                    "0.0.0.0/0"
                ],
                "outboundTag": "Reject",
                "type": "field"
            }
        ],
        "strategy": "rules"
    }
}



```
 
**客户端配置：**
无
```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

无
**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**
无
```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

无
```javascript
// 在这里附上服务器端日志

```

## 其它相关的配置文件（如 Nginx）和相关日志
无

## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出
无

## 如果 V2Ray 服务运行异常，请附上 journal 日志
无

**Comment by rurirei** [comment]
>> 通过 V2Ray DNS 服务查询 非（A AAAA） DNS 记录

unsupported.

**Comment by xiaokangwang** [comment]
您好，对于非A AAAA DNS记录，V2会默认发送至原来的服务器。 您可以链式代理dns代理协议出站到blackhole协议的出站来丢弃这些流量。

**Comment by mydogshitgold** [comment]
### If I understand you correctly.

You are using V2Ray on your gateway device and set up transparent proxy, and the port :13253 on the gateway is opened to LAN devices for DNS queries. 

> 1. The server starts v2ray
> 2. LAN user sends DNS NS record query doggo.exe @udp://server IP:13253 wsdfdf.caac -t NS
> 3. User DNS lookup failed.
> 4. In the LAN gateway intercepted to the server access 253.253.253.253:25353

And if by `server` you mean the gateway device not the upstream proxy server, you captured some outbound packets to `253.253.253.253:25353` which should not be sent.

Your goal is to have queries for A and AAAA records answered by FakeDNS and all other queries go through proxy.

### Then, your configuration is flawed
```json
{
  "port": 13253,
  "protocol": "dokodemo-door",
  "settings": {
    "address": "253.253.253.253",
    "network": "udp",
    "port": 25353
  },
  "tag": "FakeDns-In"
}
```
**253.253.253.253** is a bogon address, and will not be routed. Instead you should use a accessible public DNS server like **1.1.1.1**. I guess you use **253.253.253.253** because you want to proxy all your DNS queries.

> 3. User DNS lookup failed.
`dokodemo-door` works like routing. You DNS lookup fails because you routed DNS traffics to a non-routable address.

Change that to:
```json
{
  "port": 13253,
  "protocol": "dokodemo-door",
  "settings": {
    "address": "1.1.1.1"
    "network": "tcp,udp",
    "port": 53
  },
  "tag": "FakeDns-In"
}
```

---

```json
{
  "protocol": "dns",
  "tag": "Dns-Out"
}
```
Protocol `dns` by default does not go through proxy, unless you routed all your traffics to transparent proxy inbound. A better approach would be
```json
{
  "tag": "Dns-Out",
  "protocol": "dns",
  "proxySettings": {
    "tag": "Proxy"
  }
}
```
The "proxySettings" here is critical. It ensures that all DNS queries would be sent via inbound tagged "Proxy"

---
```json
{
  "address": "253.253.253.253",
  "inboundTag": [
    "FakeDns-In"
  ],
  "network": "udp",
  "outboundTag": "Dns-Out",
  "port": 25353,
  "type": "field"
},
```
This is redundant and cumbersome, change to
```json
{
  "outboundTag": "Dns-Out",
  "inboundTag": [
    "FakeDns-In"
  ],
  "network": "tcp,udp",
  "type": "field"
}
```
---
This way, all A and AAAA queries would be answered by V2Ray, and the reset is sent to 1.1.1.1:53/UDP through proxy. 

However, the configuration listed here probably won't work for you. Correctly forward all DNS queries to V2Ray transparently is not a trivial task, and requires coordination between V2Ray, routing tables, routing policy and firewall rules. It's a good idea to master their usage.

### The way your intercept DNS queries is suboptimal

- Only intercept UDP is insufficient. DNS client may use TCP as transport for longer responses. See [RFC 1123](https://www.rfc-editor.org/rfc/rfc1123).
- The standard port for DNS is :53 TCP or UDP, using :13253 requires changing DNS port of every LAN devices, and even worse, a lot of operating systems does not support using non-standard port for DNS at all. Ideally, to use the transparent proxy, client only need to change its default gateway.
- **172.20.0.0/16** should not be used for FakeDNS. This address block is reserved for LAN. See [Reserved IP Address](https://en.wikipedia.org/wiki/Reserved_IP_addresses). A saner choice is **198.18.0.0/15**.
- If you use **172.20.0.0/16** as IP pool to prevent **leaking** to upstream gateways, then it sadly doesn't work , the packets are still sent to your public gateway. See `traceroute 172.20.0.1`

Instead

- Route all traffics to V2Ray.
- Hijack DNS queries via firewall rules (iptables, nftables) on gateway.
- Setup V2Ray routing rules that hijacks all traffics on port :53 to DNS outbound

Some helpful artifices:
[V2Ray Tproxy (Chinese)](https://guide.v2fly.org/app/tproxy.html)
[iptables on ArchWiki (English)](https://wiki.archlinux.org/title/Iptables)
[Linux transparent proxy support (English)](https://powerdns.org/tproxydoc/tproxy.md.html)
[TPROXY documentation (English)](https://www.kernel.org/doc/html/latest/networking/tproxy.html)

**Comment by wy16W2pIilK1xgqN** [comment]
> 您好，对非AAAA DNS记录，V2会默认发送至原始的服务器。

  请教一下，我要如阻止这种情况呢？
我不能限制软件的查询，通过 v2 设置，有办法阻止发出这些地址吗？。

**Comment by xiaokangwang** [comment]
> > 您好，对非AAAA DNS记录，V2会默认发送至原始的服务器。
> 
> 请教一下，我要如阻止这种情况呢？ 我不能限制软件的查询，通过 v2 设置，有办法阻止发出这些地址吗？。

" 您可以链式代理dns代理协议出站到blackhole协议的出站来丢弃这些流量。"

**Comment by wy16W2pIilK1xgqN** [comment]
> > > 您好，对非AAAA DNS记录，V2会默认发送至原始的服务器。
> > 
> > 
> > 请教一下，我要如阻止这种情况呢？ 我不能限制软件的查询，通过 v2 设置，有办法阻止发出这些地址吗？。
> 
> " 您可以链式代理dns代理协议出站到blackhole协议的出站来丢弃这些流量。"

我尝试过这个办法，但出现的情况是正常的DNS 出站全被阻止，但依然会发出预期外的连接。
我就是到了这一半，才认为是BUG ，进而发帖的。
也许是我配置有误，能给个配置吗？

**Comment by KouYiGuo** [comment]
Please read comment of @mydogshitgold . As he said, there are two key points that you should modify your config.
Here is a sample v5 config I tested. A and AAAA record will be sent to 1.1.1.1, and the rest will be sent to 8.8.8.8. All dns queries are responded correctly.
```json
{
    "router": {
        "rule": [
            {
                "inboundTag": [
                    "dnsIn"
                ],
                "tag": "dnsOut"
            },
            {
                "inboundTag": [
                    "dnsQuery"
                ],
                "tag": "direct"
            }
        ]
    },
    "outbounds": [
        {
            "tag": "direct",
            "protocol": "freedom"
        },
        {
            "proxySettings": {
                "tag": "direct",
                "transportLayer": true
            },
            "protocol": "dns",
            "tag": "dnsOut"
        }
    ],
    "inbounds": [
        {
            "tag": "dnsIn",
            "protocol": "dokodemo-door",
            "port": 30053,
            "settings": {
                "port": 53,
                "address": "8.8.8.8",
                "networks": "tcp,udp"
            }
        }
    ],
    "dns": {
        "nameServer": [
            {
                "address": {
                    "address": "1.1.1.1"
                }
            }
        ],
        "tag": "dnsQuery"
    }
}
```

**Comment by KouYiGuo** [comment]
If you want to block dns queries except A and AAAA, consider to change 8.8.8.8 to a unreachable address OR router it to blackhole.
