### ISSUE TITLE
v5.4.1 User Preview 使用命令行模式无法正常启动

### ISSUE THREAD

**Issue by tangzhi1996** [v2fly/v2ray-core#2431]
## 你正在使用哪个版本的 V2Ray？
v5.4.1 User Preview

## 你的使用场景是什么？
仅仅是启动v2ray

## 你看到的异常现象是什么？

flag provided but not defined: -config
Usage of ./v2ray:

## 你期待看到的正常表现是怎样的？
V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/arm)
A unified platform for anti-censorship.
2023/03/22 17:26:08 Using default config:  /dev/shm/v2ray/config.json
2023/03/22 17:26:08 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
v2ctl> Read config:  /dev/shm/v2ray/config.json
2023/03/22 17:26:08 [Warning] v2ray.com/core: V2Ray 4.31.0 started

## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出

rock@rock-5b:/dev/shm/v2$ ./v2ray -test
flag provided but not defined: -test
Usage of ./v2ray:

**Comment by mydogshitgold** [comment]
The command syntax for Version 5 has been updated, requiring the use of the subcommand “run” to execute V2ray. Thus, instead of using the previous command format v2ray -config config.json, the new format requires using v2ray run -config config.json. Additionally, you now have the freedom to use alternative formats such as YAML, TOML, etc. by applying the -format flag. To receive guidance on proper command usage, you may run v2ray help.
