### ISSUE TITLE
I installed it's not readable atta all! use English language please

### ISSUE THREAD

**Issue by arminrahimian** [v2fly/v2ray-core#2433]
The Windows application has no English language and I can not read these many wonderfull lines as charachter... it's not possible to read. how can use it? please send me a english version download link please.

thank you

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by mydogshitgold** [comment]
It looks like there might be some confusion about third-party front-ends or scripts and the v2ray. Just so you know, the command-line interface of v2ray actually uses plain English. And, there's no separate English version of v2ray. If you're not sure how to use it, check out the [documentation](https://www.v2fly.org/en_US/v5/config/overview.html) for some guidance. It's probably better to ask questions in the [discussions section](https://github.com/v2fly/v2ray-core/discussions/categories/q-a) instead of the issues board. That way we can have a more productive conversation.
