### ISSUE TITLE
V2ray quic (h3) ,cloudflare solution?

### ISSUE THREAD

**Issue by mohsen-armoun** [v2fly/v2ray-core#2472]
Hi, in iran vless+grpc+tls blocked by providers 

Is that way to use cloudflare quic to send traffic?
Like grpc cdn ?

**Comment by mydogshitgold** [comment]
**No**, it's currently not possible to use the **[HTTP/3](https://en.wikipedia.org/wiki/HTTP/3#:~:text=HTTP%2F3%20is%20the%20third,%2F1.1%20and%20HTTP%2F2.)** offered by Cloudflare to reverse proxy V2Ray's traffic.


[QUIC](https://en.wikipedia.org/wiki/QUIC) is **NOT** HTTP/3 and HTTP/3 is **NOT** QUIC. 

Cloudflare does not reverse proxy QUIC traffic, which is used as the transport for application protocol HTTP/3. 

Cloudflare [**only** uses HTTP/3 from client to edge](https://developers.cloudflare.com/support/network/understanding-cloudflare-http2-and-http3-support/), not from edge to origin.

---

Theoretically, it is possible to use WebTransport, which is a web API that uses the HTTP/3 protocol as a bidirectional transport. But unfortunately, its [not implemented](https://github.com/v2fly/v2ray-core/discussions/1712#discussioncomment-2545516) by v2ray and Cloudflare [does not support it](https://github.com/cloudflare/quiche/issues/1114), yet.

---

It is possible to use Cloudflare tunnels that use QUIC as transport to forward a TCP from your client to the server.
This requires that you have control of both the domain name and the server.

---

In the future, please ask questions on the [Discussions](https://github.com/v2fly/v2ray-core/discussions) instead of the issues board. That way we can have a more productive conversation.

**Comment by mohsen-armoun** [comment]
Thanks for your answer 🫂🤝🏻🙏🏻
