### ISSUE TITLE
how to connect v2ray client in ubuntu server?

### ISSUE THREAD

**Issue by Faarhad** [v2fly/v2ray-core#2473]
Hi everybody, I've downloaded and extracted  v2ray on a Ubuntu server VM.
My aim is to pass the Ubuntu server traffic through the v2ray so it cloud bypass the censorship.
how to run the v2ray client as a service in the Ubuntu server? is there any help or documentation for this?
Thank you, guys.

**Comment by mydogshitgold** [comment]
Could you please post questions in the [Discussions](https://github.com/v2fly/v2ray-core/discussions), which is designed for this purpose, rather than in the Issues, which is reserved for bug reports?

---
> how to run the v2ray client as a service

You can create [systemd services](https://wiki.archlinux.org/title/Systemd) to start v2ray automatically. The systemd services themselves are not relevant for v2ray and should work independently of the program.

**Comment by Faarhad** [comment]
@mydogshitgold 
absolutely Sir, thanks for your reply.

**Comment by AiZahid** [comment]
Where should i apply these settings, please guide me , I'm using Ubuntu, want to bypass traffic from v2ray VPN
