### ISSUE TITLE
Adding fingerprint support for vmess direct http header

### ISSUE THREAD

**Issue by Gharib110** [v2fly/v2ray-core#2500]
Could you please add support for fingerprint for vmess direct http configs ? works good in iran

**Comment by mydogshitgold** [comment]
What is `fingerprint for vmess direct http config`?  Could you please explain more clearly and comprehensively in the body of the issue.

**Comment by Gharib110** [comment]
I have a config wich is Vmess comfig and use tcp as network and request host is set to a website which is not filtered in Iran. MCI (ISP) is scanning what address you send request to it. I realized it in Wireshark that this method have not a user-agent like Chrome or Firefox but SNI have it. I want this method support such a user-agent or fingerprint, I don't know this is possible or not. I am just asking. It is working verygood in Iran

**Comment by mydogshitgold** [comment]
> use tcp as network
> I want this method support such a user-agent or fingerprint, 

In the `tcpSettings` you can use `headers` object per [documentation](https://www.v2fly.org/config/transport/tcp.html#noneheaderobject). Unfortunately, the document itself is in Mandarin, so you may need a translator to read it.

This is a known feature. Please read the documentation before creating issues.

---

> I am just asking

Please use [Discussions board](https://github.com/v2fly/v2ray-core/discussions/categories/q-a) for question instead of issues for questions

**Comment by Gharib110** [comment]
I apologize for it. Do you know a client that support it on Android and Pc ?
I can not find these settings on V2rayNG or V2rayN for windows

**Comment by mydogshitgold** [comment]
No, typical clients don't have GUI settings for these obscure options. You have to edit the configuration manually. IIRC you can import custom json configuration into V2rayNG.
